// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "kth"
#define SECRET_PASS "pppppppp"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a30m9a7lz3e25o-ats.iot.us-east-1.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUP3CxC+xT+H3ifZHrtLuDzm4JRCwwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTE5MTIxMTA2MzYx
OFoXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXaUZpMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABNx7Djddbqa8ir3VnMSzL+ENLFy4foeQA+A8
rDAWuXYM13YlYKGcfcTilItMojKepU4ACazwgFR8OR31OXs/r5qjYDBeMB8GA1Ud
IwQYMBaAFHujdBuWWHf3cS63jDYV+YWOV5kYMB0GA1UdDgQWBBTb9r4IvH6Idht2
dVGrwh2Sq13lcTAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAViBhTM7bv47Zff9BBcqU1Zvn4sFPxTBrNiJu7cZhB4qBLlQx
tOJEmucJ39dPfI9mr2oCaLG+1XFWVIJAPkJYGXu7ILZGOlfHjPrVtj2/z2KNboIM
3fHMXcVNO2ejLucSiQ/BF5p6qqahifW6AkArZ2ThzEMs5YP9UNqI+3UEaVI9bMWF
3bdVKGSz1RIL937UImUq/m0s2xp3HMo1AVMIgwrHA9p1nPIE9EPUTHHSJL4/HPYa
7yvBY83f3CO7ygBYnHrMCGO8aju6ow1K1DviROoq4SzQTdcBussTG3ARmu+e9cpA
5HKNZJZossEu0LCjUruJV1EfNzsmhjeOVwltvg==
-----END CERTIFICATE-----
)";
